#!/usr/bin/env bash
# Builds a local, installable Android APK from this repo's own `dist/`
# build using Capacitor -- no deployed/hosted URL required. Capacitor
# bundles the built web app directly into the native project (as local
# WebView assets) rather than pointing a Trusted Web Activity at a live
# site, so this works fully offline from a checkout with no prior
# deployment step. Windows equivalent: build_apk.ps1.
#
# This replaced an earlier Bubblewrap/TWA-based script: Bubblewrap wraps a
# *deployed* PWA and verifies domain ownership via Digital Asset Links,
# which has no localhost/offline escape hatch -- it hard-blocked every APK
# build until hosting existed (see CLAUDE.md's former "Known open item").
# Capacitor trades that for two build artifacts to keep loosely in sync
# (the live site, if one ever exists, and this native bundle) -- acceptable
# here since the actual goal is a local test APK, not shipping the exact
# hosted PWA verbatim.
#
# Ships a DEBUG-signed APK (Android's auto-generated debug keystore) --
# installable straight onto a device/emulator for testing, but not eligible
# for a Play Store release. A release-signed build (your own keystore, kept
# safe forever) is a separate concern to add later if/when this is actually
# published; don't add that complexity ahead of needing it.
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

ANDROID_DIR="$REPO_ROOT/android"
OUT_DIR="$REPO_ROOT/dist-apk"
BUILD_NUMBER_FILE="$REPO_ROOT/BUILD_NUMBER"
GRADLE_FILE="$ANDROID_DIR/app/build.gradle"

if ! command -v npm >/dev/null 2>&1; then
    echo "Node.js/npm was not found on this computer."
    echo "Install it from https://nodejs.org, then run this script again."
    exit 1
fi

if ! command -v java >/dev/null 2>&1; then
    echo "Java (a JDK, 17+) was not found on PATH."
    echo "Installing Android Studio (https://developer.android.com/studio) is the"
    echo "easiest way to get one, or use https://adoptium.net directly. Re-run"
    echo "after it's on PATH."
    exit 1
fi

# The Android SDK isn't a project dependency -- Gradle just needs
# ANDROID_HOME to point at a real local install. Trust an explicitly set
# env var only if it actually resolves (a stale/wrong export, like pointing
# at a Sdk directory that was never created, shouldn't silently pass and
# then fail confusingly deep inside the Gradle build); otherwise fall back
# to this machine's known SDK location as a last resort, the same way
# coding-adventure's build_apk.sh falls back to a known Flutter install
# path when FLUTTER_HOME isn't set.
KNOWN_SDK_FALLBACK="$HOME/Android/sdk"
if [ -n "${ANDROID_HOME:-}" ] && [ -d "$ANDROID_HOME" ]; then
    :
elif [ -n "${ANDROID_SDK_ROOT:-}" ] && [ -d "$ANDROID_SDK_ROOT" ]; then
    export ANDROID_HOME="$ANDROID_SDK_ROOT"
elif [ -d "$KNOWN_SDK_FALLBACK" ]; then
    export ANDROID_HOME="$KNOWN_SDK_FALLBACK"
else
    echo "ANDROID_HOME (or ANDROID_SDK_ROOT) isn't set to a real directory."
    echo
    echo "The build needs a local Android SDK. Install Android Studio"
    echo "(https://developer.android.com/studio), open its SDK Manager once to"
    echo "download the SDK, then point the env var at it, e.g.:"
    echo
    echo '  export ANDROID_HOME="$HOME/AppData/Local/Android/Sdk"   # typical Windows path'
    echo '  export ANDROID_HOME="$HOME/Library/Android/sdk"         # typical macOS path'
    echo
    echo "and re-run."
    exit 1
fi

# On Git Bash/MSYS, a POSIX-style path (e.g. /c/Users/...) in ANDROID_HOME
# is invisible to Gradle -- it runs as a native Windows java.exe process
# that doesn't understand MSYS paths, and Gradle doesn't get the usual
# MSYS argument path-mangling since this is an environment variable *value*,
# not a command-line argument. Without this, the build fails deep inside
# Gradle with a misleading "SDK location not found" even though
# ANDROID_HOME is correctly set and the directory genuinely exists.
if command -v cygpath >/dev/null 2>&1; then
    export ANDROID_HOME="$(cygpath -w "$ANDROID_HOME")"
fi

npm install --no-audit --no-fund --quiet
npm run icons
npm run build

if [ ! -d "$ANDROID_DIR" ]; then
    echo "First-time Capacitor Android setup for Wordventure Bingo..."
    npx cap add android
fi
npx cap sync android
chmod +x "$ANDROID_DIR/gradlew" 2>/dev/null || true

# Regenerates the native launcher icon (mipmap-* + adaptive icon XML) from
# assets/icon.png every build -- android/ is gitignored and fully
# regenerated by `cap add`, so the default Capacitor icon would otherwise
# silently come back on a clean checkout.
npx @capacitor/assets generate --android

# Android requires versionCode to strictly increase between installs of the
# same package -- BUILD_NUMBER is a plain repo-root counter (tracked in git,
# same convention this app's other build scripts use), bumped here and
# written into android/app/build.gradle before every build. versionName
# tracks package.json's "version" so the two never drift.
PREV_BUILD=0
[ -f "$BUILD_NUMBER_FILE" ] && PREV_BUILD="$(cat "$BUILD_NUMBER_FILE")"
NEW_BUILD=$((PREV_BUILD + 1))
echo "$NEW_BUILD" > "$BUILD_NUMBER_FILE"

APP_VERSION="$(node -p "require('./package.json').version")"
sed -i -E "s/versionCode [0-9]+/versionCode $NEW_BUILD/" "$GRADLE_FILE"
sed -i -E "s/versionName \"[^\"]*\"/versionName \"$APP_VERSION\"/" "$GRADLE_FILE"

echo
echo "Building Android APK (v$APP_VERSION build $NEW_BUILD)..."
echo

(cd "$ANDROID_DIR" && ./gradlew assembleDebug)

mkdir -p "$OUT_DIR"
BUILT_APK="$ANDROID_DIR/app/build/outputs/apk/debug/app-debug.apk"
TAGGED_APK="$OUT_DIR/wordventure-bingo-v${APP_VERSION}-build${NEW_BUILD}-debug.apk"
if [ -f "$BUILT_APK" ]; then
    mv "$BUILT_APK" "$TAGGED_APK"
    echo
    echo "Done -- APK at $TAGGED_APK"
    echo "Install it with: adb install \"$TAGGED_APK\""
else
    echo
    echo "Gradle reported success but $BUILT_APK wasn't found."
    echo "Check android/app/build/outputs/apk/ for the actual output path."
fi
